info:
  app:
    name: Vacinas
    description: Vacinas

server:
  port: 80

scheduled:
  cron: 0 0 * * * *

spring:
  datasource:
    driver: org.postgresql.postgresql
    url: jdbc:postgresql://ec2-3-89-214-80.compute-1.amazonaws.com:5432/dc57g6j7gec31j?stringtype=unspecified
    username: rwpefjvhdeaqkk
    password: f1adb2289d4ae45e0f9646fb24263015d4c1391d6202f16144890fa54c309db5