info:
  app:
    name: Vacinas
    description: Vacinas

server:
  port: ${PORT:8090}

scheduled:
  cron: 0 0 * * * *

spring:
  datasource:
    driver: org.postgresql.Driver
    url: $(DATABASE_URL)
    username: $(DATABASE_USERNAME)
    password: $(DATABASE_PASSWORD)
